server:
  port: 8888
app:
  api-prefix: /api/v1
  prefix-strip: 2

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: identity-service
                  uri: http://localhost:8080
                  predicates:
                      - Path=${app.api-prefix}/identity/**
                  filters:
                    - StripPrefix= ${app.prefix-strip}

                - id: profile-service
                  uri: http://localhost:8081
                  predicates:
                    - Path=${app.api-prefix}/profile/**
                  filters:
                    - StripPrefix= ${app.prefix-strip}


