server:
  port: 8888
app:
  profile-service-url: http://localhost:8081
  identity-service-url: http://localhost:8080
  notification-service-url: http://localhost:8082
  api-prefix: /api/v1
  prefix-strip: 2

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: identity-service
                  uri: ${app.identity-service-url}
                  predicates:
                      - Path=${app.api-prefix}/identity/**
                  filters:
                    - StripPrefix= ${app.prefix-strip}

                - id: profile-service
                  uri: ${app.profile-service-url}
                  predicates:
                    - Path=${app.api-prefix}/profile/**
                  filters:
                    - StripPrefix= ${app.prefix-strip}

                - id: notification-service
                  uri: ${app.notification-service-url}
                  predicates:
                    - Path=${app.api-prefix}/notification/**
                  filters:
                    - StripPrefix= ${app.prefix-strip}


